trigger:
  branches:
    include:
      - main

variables:
  imageName: 'claim-status-api'
  acrName: 'prathapacr'
  resourceGroup: 'prathapRG'
  containerAppName: 'claim-status-app'
  apimName: 'claim-status-apim'
  location: 'eastus'

stages:
# -------------------
# 1. Build Stage
# -------------------
- stage: Build
  displayName: Build and Push using az acr build
  jobs:
  - job: Build
    pool:
      name: Default
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build Docker Image in ACR
      inputs:
        azureSubscription: 'genai-devops-svc-ch-1'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr build --registry $(acrName) --image $(imageName):$(Build.BuildId) src/

# -------------------
# 2. Security Scan Stage
# -------------------
- stage: SecurityScan
  displayName: Security Scan
  dependsOn: Build
  jobs:
  - job: Scan
    pool:
      name: Default
    steps:
    - task: PowerShell@2
      displayName: "Info: Defender for Containers enabled"
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Defender for Containers will auto-scan the image in ACR."

    - task: PowerShell@2
      displayName: "Run Trivy Scan"
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.ps1 -OutFile install-trivy.ps1
          .\install-trivy.ps1
          .\trivy.exe image --exit-code 1 --severity CRITICAL,HIGH $(acrName).azurecr.io/$(imageName):$(Build.BuildId)

# -------------------
# 3. Deploy Stage
# -------------------
- stage: Deploy
  displayName: Deploy ACA and APIM using Bicep
  dependsOn: SecurityScan
  jobs:
  - job: Deploy
    pool:
      name: Default
    steps:
    - task: PowerShell@2
      displayName: "Run Trivy Scan"
      inputs:
        targetType: 'inline'
        script: |
          $trivyUrl = "https://github.com/aquasecurity/trivy/releases/download/v0.66.0/trivy_0.66.0_Windows-64bit.zip"
          $zipPath = "$(System.DefaultWorkingDirectory)\trivy.zip"
          $extractPath = "$(System.DefaultWorkingDirectory)\trivy"

          Write-Host "Downloading Trivy from $trivyUrl"
          Invoke-WebRequest -Uri $trivyUrl -OutFile $zipPath

          Write-Host "Extracting Trivy..."
          Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force

          $trivyExe = Join-Path $extractPath "trivy.exe"
          Write-Host "Running Trivy scan..."
          & $trivyExe image --exit-code 1 --severity CRITICAL,HIGH "$(acrName).azurecr.io/$(imageName):$(Build.BuildId)"