trigger:
  branches:
    include:
      - main

variables:
  imageName: 'claim-status-api'
  acrName: 'prathapacr'
  resourceGroup: 'prathapRG'
  containerAppName: 'claim-status-app'
  apimName: 'claim-status-apim'
  location: 'eastus'

stages:
# -------------------
# 1. Build Stage
# -------------------
- stage: Build
  displayName: Build and Push Docker Image using ACR Build
  jobs:
  - job: Build
    pool:
      name: Default
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build and Push using az acr build
      inputs:
        azureSubscription: 'genai-devops-svc-ch-1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr build --registry $(acrName) --image $(imageName):$(Build.BuildId) pipelines/src/

# -------------------
# 2. Security Scan Stage
# -------------------
- stage: SecurityScan
  displayName: Security Scan
  dependsOn: Build
  jobs:
  - job: Scan
    pool:
      name: Default
    steps:
    - script: |
        echo "Defender for Containers will auto-scan the image in ACR."
      displayName: "Info: Defender for Containers enabled"

    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        ./trivy image --exit-code 1 --severity CRITICAL,HIGH $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
      displayName: "Run Trivy Scan"

# -------------------
# 3. Deploy Stage
# -------------------
- stage: Deploy
  displayName: Deploy ACA and APIM using Bicep
  dependsOn: SecurityScan
  jobs:
  - job: Deploy
    pool:
      name: Default
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'genai-devops-svc-ch-1'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroup) --location $(location)
          az deployment group create  --resource-group $(resourceGroup) --template-file pipelines/infra/main.bicep             --parameters containerAppName=$(containerAppName)                          containerImage=$(acrName).azurecr.io/$(imageName):$(Build.BuildId)                          acrName=$(acrName)                          apimName=$(apimName)
