name: Trigger auto deployment for claim-status-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/claim-status-app-AutoDeployTrigger-db628b47-c240-409a-87eb-b5bcfa94da36.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLAIMSTATUSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLAIMSTATUSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLAIMSTATUSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}src
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: prathapacr.azurecr.io
          registryUsername: ${{ secrets.CLAIMSTATUSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLAIMSTATUSAPP_REGISTRY_PASSWORD }}
          containerAppName: claim-status-app
          resourceGroup: prathapRG
          imageToBuild: prathapacr.azurecr.io/claim-status-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


