name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: claim-status-api
  ACR_NAME: prathapacr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name $ACR_NAME

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${{ github.run_id }}
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG -f src/Dockerfile src
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

    - name: Deploy to Azure Container Apps
      run: |
        IMAGE_TAG=${{ github.run_id }}
        az containerapp update \
          --name claim-status-app \
          --resource-group prathapRG \
          --image $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
